"use client";

import React, { useState } from 'react';
import { Button } from '@/components/ui/Button';
import { 
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
  DropdownMenuLabel
} from '@/components/ui/DropdownMenu';
import { Download, FileText, FileSpreadsheet, FileImage, FileJson, ChevronDown } from 'lucide-react';
import { ExtendedPoVDetails } from '@/lib/pov/hooks/usePOVList';
import { fromLocalYmd } from '@/lib/utils/local-date';

interface POVExportButtonProps {
  povs: ExtendedPoVDetails[];
  filename?: string;
  className?: string;
}

export function POVExportButton({ 
  povs, 
  filename = 'povs_export',
  className = ''
}: POVExportButtonProps) {
  const [isExporting, setIsExporting] = useState(false);

  // Common data preparation
  const prepareData = () => {
    return povs.map(pov => ({
      title: pov.title,
      status: pov.status,
      priority: pov.priority,
      startDate: fromLocalYmd(pov.startDate).toLocaleDateString(),
      endDate: fromLocalYmd(pov.endDate).toLocaleDateString(),
      revenue: pov.revenue ? `$${pov.revenue}` : '',
      customer: pov.customerName || '',
      owner: pov.owner?.name || '',
      theatre: pov.salesTheatre || '',
      country: pov.country?.name || '',
      region: pov.region?.name || '',
      description: pov.description || '',
      opportunityName: pov.opportunityName || '',
      forecastDate: pov.forecastDate ? fromLocalYmd(pov.forecastDate).toLocaleDateString() : '',
      createdAt: new Date(pov.createdAt).toLocaleDateString(),
      updatedAt: new Date(pov.updatedAt).toLocaleDateString()
    }));
  };

  // CSV Export
  const exportToCSV = async () => {
    setIsExporting(true);
    try {
      const headers = [
        'Title', 'Status', 'Priority', 'Start Date', 'End Date', 'Revenue',
        'Customer', 'Owner', 'Theatre', 'Country', 'Region', 'Description',
        'Opportunity', 'Forecast Date', 'Created', 'Updated'
      ];
      
      const data = prepareData();
      const rows = data.map(row => [
        row.title, row.status, row.priority, row.startDate, row.endDate,
        row.revenue, row.customer, row.owner, row.theatre, row.country,
        row.region, row.description, row.opportunityName, row.forecastDate,
        row.createdAt, row.updatedAt
      ]);
      
      const csvContent = [
        headers.join(','),
        ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
      ].join('\n');
      
      downloadFile(csvContent, `${filename}_${getTimestamp()}.csv`, 'text/csv');
    } finally {
      setIsExporting(false);
    }
  };

  // Excel Export (CSV with Excel-specific formatting)
  const exportToExcel = async () => {
    setIsExporting(true);
    try {
      const headers = [
        'Title', 'Status', 'Priority', 'Start Date', 'End Date', 'Revenue',
        'Customer', 'Owner', 'Theatre', 'Country', 'Region', 'Description',
        'Opportunity', 'Forecast Date', 'Created', 'Updated'
      ];
      
      const data = prepareData();
      const rows = data.map(row => [
        row.title, row.status, row.priority, row.startDate, row.endDate,
        row.revenue, row.customer, row.owner, row.theatre, row.country,
        row.region, row.description, row.opportunityName, row.forecastDate,
        row.createdAt, row.updatedAt
      ]);
      
      // Excel-compatible CSV with BOM for proper UTF-8 encoding
      const csvContent = '\uFEFF' + [
        headers.join(','),
        ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
      ].join('\n');
      
      downloadFile(csvContent, `${filename}_${getTimestamp()}.csv`, 'text/csv');
    } finally {
      setIsExporting(false);
    }
  };

  // Markdown Export
  const exportToMarkdown = async () => {
    setIsExporting(true);
    try {
      const data = prepareData();
      
      // Create Markdown content
      const markdownContent = `# POV Export Report

**Export Date:** ${new Date().toLocaleDateString()}  
**Total POVs:** ${data.length}  
**Generated by:** POV Management System

---

## Summary

This report contains ${data.length} POV records with current filters and sorting applied.

## POV Details

| Title | Status | Priority | Revenue | Customer | Owner | Theatre | Start Date | End Date |
|-------|--------|----------|---------|----------|-------|---------|------------|----------|
${data.map(row => `| ${row.title} | ${row.status} | ${row.priority} | ${row.revenue} | ${row.customer} | ${row.owner} | ${row.theatre} | ${row.startDate} | ${row.endDate} |`).join('\n')}

---

## Additional Information

${data.map((row, index) => `
### ${index + 1}. ${row.title}

- **Status:** ${row.status}
- **Priority:** ${row.priority}
- **Revenue:** ${row.revenue}
- **Customer:** ${row.customer}
- **Owner:** ${row.owner}
- **Theatre:** ${row.theatre}
- **Country:** ${row.country}
- **Region:** ${row.region}
- **Start Date:** ${row.startDate}
- **End Date:** ${row.endDate}
- **Forecast Date:** ${row.forecastDate}
- **Description:** ${row.description}
- **Opportunity:** ${row.opportunityName}
- **Created:** ${row.createdAt}
- **Updated:** ${row.updatedAt}

---
`).join('')}

*Report generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}*
`;
      
      downloadFile(markdownContent, `${filename}_${getTimestamp()}.md`, 'text/markdown');
    } finally {
      setIsExporting(false);
    }
  };

  // PDF Export (using HTML to PDF conversion)
  const exportToPDF = async () => {
    setIsExporting(true);
    try {
      const data = prepareData();
      
      // Create HTML content for PDF
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>POV Export Report</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            h1 { color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }
            .summary { background: #f5f5f5; padding: 15px; margin: 20px 0; border-radius: 5px; }
            table { width: 100%; border-collapse: collapse; margin: 20px 0; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f2f2f2; font-weight: bold; }
            tr:nth-child(even) { background-color: #f9f9f9; }
            .footer { margin-top: 30px; font-size: 12px; color: #666; }
          </style>
        </head>
        <body>
          <h1>POV Export Report</h1>
          <div class="summary">
            <p><strong>Export Date:</strong> ${new Date().toLocaleDateString()}</p>
            <p><strong>Total POVs:</strong> ${data.length}</p>
            <p><strong>Generated by:</strong> POV Management System</p>
          </div>
          <table>
            <thead>
              <tr>
                <th>Title</th>
                <th>Status</th>
                <th>Priority</th>
                <th>Revenue</th>
                <th>Customer</th>
                <th>Owner</th>
                <th>Theatre</th>
                <th>Start Date</th>
                <th>End Date</th>
              </tr>
            </thead>
            <tbody>
              ${data.map(row => `
                <tr>
                  <td>${row.title}</td>
                  <td>${row.status}</td>
                  <td>${row.priority}</td>
                  <td>${row.revenue}</td>
                  <td>${row.customer}</td>
                  <td>${row.owner}</td>
                  <td>${row.theatre}</td>
                  <td>${row.startDate}</td>
                  <td>${row.endDate}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div class="footer">
            <p>This report contains ${data.length} POV records exported on ${new Date().toLocaleDateString()}</p>
          </div>
        </body>
        </html>
      `;
      
      // For now, we'll save as HTML (can be opened in browser and printed to PDF)
      // In a real implementation, you might use a library like jsPDF or puppeteer
      downloadFile(htmlContent, `${filename}_${getTimestamp()}.html`, 'text/html');
    } finally {
      setIsExporting(false);
    }
  };

  // HTML Export
  const exportToHTML = async () => {
    setIsExporting(true);
    try {
      const data = prepareData();
      
      // Create standalone HTML content
      const htmlContent = `
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>POV Export Report</title>
          <style>
            body { 
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
              margin: 0; 
              padding: 20px; 
              background: #f8f9fa; 
            }
            .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            h1 { color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 15px; margin-bottom: 30px; }
            .summary { 
              background: linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%); 
              padding: 20px; 
              margin: 20px 0; 
              border-radius: 8px; 
              border-left: 4px solid #2563eb;
            }
            .summary h2 { margin-top: 0; color: #1e40af; }
            table { 
              width: 100%; 
              border-collapse: collapse; 
              margin: 30px 0; 
              box-shadow: 0 1px 3px rgba(0,0,0,0.1);
              border-radius: 8px;
              overflow: hidden;
            }
            th, td { 
              border: 1px solid #e5e7eb; 
              padding: 12px 8px; 
              text-align: left; 
              font-size: 14px;
            }
            th { 
              background: linear-gradient(135deg, #1e40af 0%, #2563eb 100%); 
              color: white; 
              font-weight: 600; 
              text-transform: uppercase;
              font-size: 12px;
              letter-spacing: 0.5px;
            }
            tr:nth-child(even) { background-color: #f9fafb; }
            tr:hover { background-color: #f3f4f6; }
            .footer { 
              margin-top: 40px; 
              padding-top: 20px;
              border-top: 1px solid #e5e7eb;
              font-size: 12px; 
              color: #6b7280; 
              text-align: center;
            }
            .status { padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: 500; }
            .status-projected { background: #dbeafe; color: #1e40af; }
            .status-in-progress { background: #fef3c7; color: #92400e; }
            .status-completed { background: #d1fae5; color: #065f46; }
            .priority { padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: 500; }
            .priority-high { background: #fee2e2; color: #991b1b; }
            .priority-medium { background: #fef3c7; color: #92400e; }
            .priority-low { background: #e0f2fe; color: #0c4a6e; }
            @media print {
              body { background: white; }
              .container { box-shadow: none; }
            }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>📊 POV Export Report</h1>
            <div class="summary">
              <h2>Report Summary</h2>
              <p><strong>Export Date:</strong> ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}</p>
              <p><strong>Total POVs:</strong> ${data.length} records</p>
              <p><strong>Generated by:</strong> POV Management System</p>
              <p><strong>Filters Applied:</strong> Current view filters and sorting included</p>
            </div>
            <table>
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Status</th>
                  <th>Priority</th>
                  <th>Revenue</th>
                  <th>Customer</th>
                  <th>Owner</th>
                  <th>Theatre</th>
                  <th>Start Date</th>
                  <th>End Date</th>
                  <th>Country</th>
                </tr>
              </thead>
              <tbody>
                ${data.map(row => `
                  <tr>
                    <td><strong>${row.title}</strong></td>
                    <td><span class="status status-${row.status.toLowerCase().replace(' ', '-')}">${row.status}</span></td>
                    <td><span class="priority priority-${row.priority.toLowerCase()}">${row.priority}</span></td>
                    <td><strong>${row.revenue}</strong></td>
                    <td>${row.customer}</td>
                    <td>${row.owner}</td>
                    <td>${row.theatre}</td>
                    <td>${row.startDate}</td>
                    <td>${row.endDate}</td>
                    <td>${row.country}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
            <div class="footer">
              <p>This report contains ${data.length} POV records exported on ${new Date().toLocaleDateString()}</p>
              <p>Generated by POV Management System • Print-friendly format available</p>
            </div>
          </div>
        </body>
        </html>
      `;
      
      downloadFile(htmlContent, `${filename}_${getTimestamp()}.html`, 'text/html');
    } finally {
      setIsExporting(false);
    }
  };

  // Utility functions
  const getTimestamp = () => {
    return new Date().toISOString().split('T')[0];
  };

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const exportOptions = [
    {
      label: 'CSV (Comma-Separated)',
      description: 'Best for spreadsheet applications',
      icon: FileSpreadsheet,
      action: exportToCSV,
      format: 'CSV'
    },
    {
      label: 'Excel Compatible',
      description: 'Optimized for Microsoft Excel',
      icon: FileSpreadsheet,
      action: exportToExcel,
      format: 'Excel'
    },
    {
      label: 'Markdown Report',
      description: 'Documentation-friendly format',
      icon: FileText,
      action: exportToMarkdown,
      format: 'Markdown'
    },
    {
      label: 'PDF Report',
      description: 'Formatted report document',
      icon: FileText,
      action: exportToPDF,
      format: 'PDF'
    },
    {
      label: 'HTML Report',
      description: 'Styled web page format',
      icon: FileText,
      action: exportToHTML,
      format: 'HTML'
    }
  ];

  if (povs.length === 0) {
    return (
      <Button variant="outline" size="sm" disabled className={className}>
        <Download className="h-4 w-4 mr-2" />
        Export
      </Button>
    );
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button 
          variant="outline" 
          size="sm" 
          className={`gap-1 ${className}`}
          disabled={isExporting}
        >
          <Download className="h-4 w-4" />
          <span>Export</span>
          <ChevronDown className="h-3 w-3" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-64">
        <DropdownMenuLabel className="text-xs">
          Export {povs.length} POV{povs.length !== 1 ? 's' : ''}
        </DropdownMenuLabel>
        <DropdownMenuSeparator />
        
        {exportOptions.map((option, index) => {
          const IconComponent = option.icon;
          return (
            <DropdownMenuItem
              key={index}
              onClick={option.action}
              disabled={isExporting}
              className="flex flex-col items-start p-3 cursor-pointer"
            >
              <div className="flex items-center gap-2 w-full">
                <IconComponent className="h-4 w-4" />
                <div className="flex-1">
                  <div className="font-medium text-sm">{option.label}</div>
                  <div className="text-xs text-muted-foreground">{option.description}</div>
                </div>
              </div>
            </DropdownMenuItem>
          );
        })}
        
        <DropdownMenuSeparator />
        <div className="px-3 py-2 text-xs text-muted-foreground">
          Files will include current filters and sorting
        </div>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

export default POVExportButton;
