import { NextRequest, NextResponse } from 'next/server';
import { getAuthUser } from '@/lib/auth/get-auth-user';
import { prisma } from '@/lib/prisma';
import { MCPRecommendationStatus } from '@prisma/client';
import { parseEnumParam } from '@/lib/utils/parse-enum-param';
import { mcpLogger } from '@/lib/logger';

/**
 * GET /api/mcp/service-recommendations
 *
 * Fetch auto-generated MCP service workflow recommendations from database.
 * Complements hardcoded recommendations in RecommendationEngine.tsx
 *
 * Query params:
 * - serviceId: Filter by specific service
 * - status: Filter by recommendation status (PENDING, APPROVED, etc.)
 * - limit: Max recommendations to return (default: 20)
 *
 * Security: Requires authentication
 */
export async function GET(request: NextRequest) {
  try {
    // Authenticate user
    const user = await getAuthUser(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const serviceId = searchParams.get('serviceId');
    // 2026-05-27 (pentest M-2 sibling): validate before the Prisma where (cast → 500 on bad value)
    const status = parseEnumParam(searchParams.get('status'), MCPRecommendationStatus);
    const limit = Math.min(parseInt(searchParams.get('limit') || '20', 10) || 20, 200); // BC41 FIX: cap limit

    // Cross-tenant fix (2026-05-26 round 2): non-admins see only their own
    // recommendations + global (null-userId) ones — never another user's.
    // Recommendations embed task/POV titles in actions[], so the prior unscoped
    // findMany leaked cross-tenant content to any authenticated caller.
    const isAdmin = user.role === 'ADMIN' || user.role === 'SUPER_ADMIN';
    const where: {
      toolId?: string;
      status?: MCPRecommendationStatus;
      OR?: Array<{ userId: string | null }>;
    } = {};

    if (!isAdmin) where.OR = [{ userId: user.userId }, { userId: null }];
    if (serviceId) where.toolId = serviceId;
    if (status) where.status = status;

    const recommendations = await prisma.mCPRecommendation.findMany({
      where,
      include: {
        tool: {
          select: {
            id: true,
            name: true,
            capabilities: true
          }
        }
      },
      orderBy: [
        { impact: 'desc' },
        { confidence: 'desc' },
        { createdAt: 'desc' }
      ],
      take: limit
    });

    // Transform to format expected by frontend
    const formatted = recommendations.map(rec => ({
      id: rec.id,
      type: rec.type.toLowerCase().replace(/_/g, '-'), // WORKFLOW_IMPROVEMENT → workflow-improvement
      title: rec.title,
      description: rec.description,
      impact: rec.impact.toLowerCase() as 'high' | 'medium' | 'low',
      services: [rec.tool.name],
      suggestedSteps: rec.actions as Array<{
        service: string;
        tool: string;
        arguments?: Record<string, unknown>;
      }>,
      confidence: rec.confidence,
      effort: rec.effort,
      status: rec.status,
      autoGenerated: true
    }));

    return NextResponse.json({
      success: true,
      count: formatted.length,
      data: formatted
    });
  } catch (error) {
    mcpLogger.error({ err: error }, 'Failed to fetch service recommendations');
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to fetch recommendations'
      },
      { status: 500 }
    );
  }
}

/**
 * POST /api/mcp/service-recommendations/generate
 *
 * Trigger recommendation generation for a specific service.
 * Admin-only endpoint.
 *
 * Security: Requires ADMIN or SUPER_ADMIN role
 */
export async function POST(request: NextRequest) {
  try {
    // Authenticate user
    const user = await getAuthUser(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Check admin permissions
    if (user.role !== 'ADMIN' && user.role !== 'SUPER_ADMIN') {
      return NextResponse.json(
        { error: 'Forbidden - Admin access required' },
        { status: 403 }
      );
    }

    const body = await request.json();
    const { serviceId } = body;

    if (!serviceId) {
      return NextResponse.json(
        { success: false, error: 'serviceId required' },
        { status: 400 }
      );
    }

    // Import generator
    const { autoGenerateRecommendations } = await import('@/lib/mcp/recommendation-generator');

    // Generate recommendations
    const count = await autoGenerateRecommendations(serviceId, prisma);

    return NextResponse.json({
      success: true,
      message: `Generated ${count} recommendations for service ${serviceId}`,
      count
    });
  } catch (error) {
    mcpLogger.error({ err: error }, 'Failed to generate service recommendations');
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to generate recommendations'
      },
      { status: 500 }
    );
  }
}
