#!/usr/bin/env python3
"""
render-public-claude — generate CLAUDE.public.md (exported as CLAUDE.md) from the private CLAUDE.md.
Section ALLOWLIST: the operating protocols, agent map, dev commands and architecture cross; the two
sections that are production procedure (SSH, psql, deploy runbooks, scheduled health-runs) do not.
Then line-level scrubs for anything prod-specific, and a check that every `.claude/…` path it cites
survives the export rules. Regenerate after editing CLAUDE.md; never hand-edit the output.
"""
import re, subprocess, sys, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = open(os.path.join(ROOT, 'CLAUDE.md'), encoding='utf-8').read()
parts = re.split(r'(?m)^(?=## )', src); head, secs = parts[0], parts[1:]
KEEP = ['## 🤝 Collaboration Principles', '## ✍️ Commit Attribution', '## 🔍 IMPORTANT: Discovery-First Workflow',
        '## 📖 Understanding: The 4-Layer System', '## 🔍 Protocol 1', '## 🎯 Protocol 2', '## 🔄 Protocol 3',
        '## 🔒 Protocol 4', '## 🐛 Protocol 6', '## 🔬 Protocol 7', '## 🔁 Protocol 8', '## ⬆️ Protocol 9',
        '## 🪧 Protocol 10', '## 🧹 Protocol 11', '## 📚 Protocol Summary', '## 🔧 Toolkit',
        '## Development Commands', '## Architecture Overview']
# Protocol 5 (forensic investigation) is a production-log runbook — dropped with its section.
kept = [s for s in secs if any(s.startswith(k) for k in KEEP)]
out = head + ''.join(kept)
out = re.sub(r'(?m)^.*(137\.184\.247\.110|ssh root@|psql "\$DATABASE_URL"|BASE_URL=https://paichart\.app|PAICHART_MONITOR_TOKEN|cline_docs|smoke-tests|phase-3-jwt-deployment-readiness).*\n', '', out)
out = re.sub(r'(?m)^\| 5\. Forensic Investigation \|.*\n', '', out)   # summary-table row for the dropped protocol
out = out.replace('**Protocols**: `/.claude/knowledge/protocols/`', '**Protocols**: `/.claude/knowledge/protocols/`')
banner = ('<!-- PUBLIC VARIANT — generated by scripts/render-public-claude.py from the private CLAUDE.md by section\n'
          '     allowlist. The private one carries production procedures (SSH, psql, deploy runbooks) that never\n'
          '     cross. Regenerate after editing CLAUDE.md; do not hand-edit this file. -->\n')
open(os.path.join(ROOT, 'CLAUDE.public.md'), 'w', encoding='utf-8').write(banner + out)
# every cited .claude path must survive the export rules
rules = subprocess.run([sys.executable, '-c', '''
import sys; sys.path.insert(0, "scripts"); import importlib.util
spec = importlib.util.spec_from_file_location("x", "scripts/export-public.py"); m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
rules = m.load_rules(); wired = set()
import re
cited = sorted(set(p.strip("`/") for p in re.findall(r"`/?\\.claude/[A-Za-z0-9_./-]+`", open("CLAUDE.public.md").read())))
import os
for p in cited:
    if os.path.isdir(p):
        ok = any(m.decide(os.path.join(p, f), rules, wired)[0] for f in os.listdir(p) if os.path.isfile(os.path.join(p, f)))
    else:
        ok = os.path.exists(p) and m.decide(p, rules, wired)[0]
    if not ok: print("DANGLING:", p)
'''], cwd=ROOT, capture_output=True, text=True)
print(rules.stdout.strip() or 'all cited .claude paths survive the export rules')
print(f"CLAUDE.public.md: {len(kept)}/{len(secs)} sections, {out.count(chr(10))} lines")
